### ISSUE TITLE
listPath() is not my friend

### ISSUE THREAD

**Issue by humberry** [humberry/smb-example#1]
Although upload, download and delete works, I've always trouble with listPath(service_name, path, search=55, pattern='*', timeout=30). No idea why!

**Comment by cclauss** [comment]
What is the error message??  It is difficult to isolate the problem without that vital clue.

Try to reformulate `getRemoteDir()`:

``` python
def getRemoteDir(username, password, my_name, remote_name, remote_ip, path, pattern, service_name):
    print('getRemoteDir() starts...')
    conn = connect(username, password, my_name, remote_name, remote_ip)
    if conn:
        try:
            files = conn.listPath(service_name, path, pattern=pattern)
            #files = conn.listPath(service_name, path)
            print('returning: {}'.format(files))
            return files
        except Exception, e:
            fmt = 'conn.listPath({}, {}, {}) threw {}: {}'
            print(fmt.format(service_name, path, pattern, type(e), e))
        finally:
            conn.close()
    else
        print('connect() failed!')
    return None
```

**Comment by humberry** [comment]
This is the correct response (only 2 out of 100 tries worked):
.
..
.Thumbs
raspi-guide.pdf

And most of the time I get this long exception (you can find at the end of each smb message the ascii text I found):
Failed to list \share\ on USBDisk1_Volume1: Unable to retrieve file list
==================== SMB Message 0 ====================

## SMB Header:

Command: 0x75 (SMB_COM_TREE_CONNECT_ANDX) 
Status: NTSTATUS=0x00000000 
Flags: 0x18 
Flags2: 0xC807 
PID: 3278 
UID: 101 
MID: 4 
TID: 0 
Security: 0x0000000000000000 
Parameters: 8 bytes 
ff0000000c000100 
Data: 55 bytes 
005c005c0054004d00300032005c005500530042004400690073006b0031005f0056006f006c0075006d006500310000003f3f3f3f3f00 

## SMB Data Packet (hex):

ff534d4275000000001807c80000000000000000000000000000ce0c6500040004ff0000000c0001003700005c005c0054004d00300032005c005500530042004400690073006b0031005f0056006f006c0075006d006500310000003f3f3f3f3f00
(ASCII: \TM02\USBDisk1_Volume1 ????? SMBu)
==================== SMB Message 1 ====================

## SMB Header:

Command: 0x75 (SMB_COM_TREE_CONNECT_ANDX) 
Status: NTSTATUS=0x00000000 
Flags: 0x88 
Flags2: 0xC801 
PID: 3278 
UID: 101 
MID: 4 
TID: 1 
Security: 0x0000000000000000 
Parameters: 6 bytes 
ff0000000300 
Data: 13 bytes 
413a004e005400460053000000 

## SMB Data Packet (hex):

ff534d4275000000008801c80000000000000000000000000100ce0c6500040003ff00000003000d00413a004e005400460053000000
(ASCII: A: NTFS SMBu)
==================== SMB Message 2 ====================

## SMB Header:

Command: 0x32 (SMB_COM_TRANSACTION2) 
Status: NTSTATUS=0x00000000 
Flags: 0x18 
Flags2: 0xC807 
PID: 3278 
UID: 101 
MID: 5 
TID: 1 
Security: 0x0000000000000000 
Parameters: 30 bytes 
200000000a00044100000000000000000000200044000000000001000100 
Data: 35 bytes 
0000003700640006000401000000005c00730068006100720065005c002a002e002a00 

## SMB Data Packet (hex):

ff534d4232000000001807c80000000000000000000000000100ce0c650005000f200000000a0004410000000000000000000020004400000000000100010023000000003700640006000401000000005c00730068006100720065005c002a002e002a00
(ASCII: \share*.\* SMB2)
==================== SMB Message 3 ====================

## SMB Header:

Command: 0x32 (SMB_COM_TRANSACTION2) 
Status: NTSTATUS=0xC000000F 
Flags: 0x88 
Flags2: 0xC841 
PID: 3278 
UID: 101 
MID: 5 
TID: 1 
Security: 0x0000000000000000 
Parameters: 0 bytes 

Data: 0 bytes 

## SMB Data Packet (hex):

ff534d42320f0000c08841c80000000000000000000000000100ce0c65000500000000
(ASCII: SMB2)

**Comment by humberry** [comment]
Okay and now with the new getRemoteDir():
getRemoteDir() starts...
conn.listPath(USBDisk1_Volume1, /share/, *.*) threw <class 'smb.smb_structs.OperationFailure'>: Failed to list \share\ on USBDisk1_Volume1: Unable to retrieve file list
==================== SMB Message 0 ====================

## SMB Header:

Command: 0x75 (SMB_COM_TREE_CONNECT_ANDX) 
Status: NTSTATUS=0x00000000 
Flags: 0x18 
Flags2: 0xC807 
PID: 3278 
UID: 101 
MID: 4 
TID: 0 
Security: 0x0000000000000000 
Parameters: 8 bytes 
ff0000000c000100 
Data: 55 bytes 
005c005c0054004d00300032005c005500530042004400690073006b0031005f0056006f006c0075006d006500310000003f3f3f3f3f00 

## SMB Data Packet (hex):

ff534d4275000000001807c80000000000000000000000000000ce0c6500040004ff0000000c0001003700005c005c0054004d00300032005c005500530042004400690073006b0031005f0056006f006c0075006d006500310000003f3f3f3f3f00
==================== SMB Message 1 ====================

## SMB Header:

Command: 0x75 (SMB_COM_TREE_CONNECT_ANDX) 
Status: NTSTATUS=0x00000000 
Flags: 0x88 
Flags2: 0xC801 
PID: 3278 
UID: 101 
MID: 4 
TID: 1 
Security: 0x0000000000000000 
Parameters: 6 bytes 
ff0000000300 
Data: 13 bytes 
413a004e005400460053000000 

## SMB Data Packet (hex):

ff534d4275000000008801c80000000000000000000000000100ce0c6500040003ff00000003000d00413a004e005400460053000000
==================== SMB Message 2 ====================

## SMB Header:

Command: 0x32 (SMB_COM_TRANSACTION2) 
Status: NTSTATUS=0x00000000 
Flags: 0x18 
Flags2: 0xC807 
PID: 3278 
UID: 101 
MID: 5 
TID: 1 
Security: 0x0000000000000000 
Parameters: 30 bytes 
200000000a00044100000000000000000000200044000000000001000100 
Data: 35 bytes 
0000003700640006000401000000005c00730068006100720065005c002a002e002a00 

## SMB Data Packet (hex):

ff534d4232000000001807c80000000000000000000000000100ce0c650005000f200000000a0004410000000000000000000020004400000000000100010023000000003700640006000401000000005c00730068006100720065005c002a002e002a00
==================== SMB Message 3 ====================

## SMB Header:

Command: 0x32 (SMB_COM_TRANSACTION2) 
Status: NTSTATUS=0xC000000F 
Flags: 0x88 
Flags2: 0xC841 
PID: 3278 
UID: 101 
MID: 5 
TID: 1 
Security: 0x0000000000000000 
Parameters: 0 bytes 

Data: 0 bytes 

## SMB Data Packet (hex):

ff534d42320f0000c08841c80000000000000000000000000100ce0c65000500000000

**Comment by cclauss** [comment]
There is a `share` directory on the disk `USBDisk1_Volume1`?  Is it read accessible to userid?

The pattern should be *, not .

**Comment by humberry** [comment]
\USBDisk1_Volume1\share\ is read/write accessible, because the uploads and downloads are okay. The pattern is "*.*", but I also tried pattern="*" (default). Sorry I didn't see the markdown result ends in only one point.

**Comment by humberry** [comment]
I also started a thread [here](https://github.com/miketeo/pysmb/issues/24).

**Comment by humberry** [comment]
Now even listPath() is my friend :).

**Comment by humberry** [comment]
Close #1
